### ISSUE TITLE
Sockets.on([model]) not working with Ember blueprints

### ISSUE THREAD

**Issue by HERRKIN** [mphasize/sails-generate-ember-blueprints#23]
I have a resource user which pluralized is users of course so when I go to the browser console and type io.sockets.on() I dont get anything when using 'user' or 'users' if I update the resource. how do I fix that?

**Comment by mphasize** [comment]
Unfortunately I cannot help you with sockets (since I know virtually nothing about them).
You may want to try looking here [Sails 0.11 socket changes](https://github.com/balderdashy/sails/blob/master/0.11-migration-guide.md) and here [Ember Data Sails](https://github.com/huafu/ember-data-sails).

If you want to see if you can fix the issue yourself, a good starting point may be here (if you're using the 'advanced` flavor): 
https://github.com/mphasize/sails-generate-ember-blueprints/blob/master/templates/advanced/api/blueprints/find.js#L67

**Comment by mphasize** [comment]
@HERRKIN could you find a solution?
